using System;
using System.Collections.Generic;
using UnityEngine;

// annoyingly the below code was generated by Copilot by searching for "PointSetRegistration for unity C#" in MS Edge
// I have overviewed and modified the code to fit my purpose, however the core code was taken from AI

public class PointSetRegistration : MonoBehaviour
{
    // Example point sets (replace with your own data)
    public List<Vector3> sourcePoints;
    public List<Vector3> targetPoints;

    [Range(1, 100)]
    public int maxIterations = 50;
    public float tolerance = 1e-5f;

    //void Start()
    //{
    //    if (sourcePoints.Count != targetPoints.Count || sourcePoints.Count == 0)
    //    {
    //        Debug.LogError("Source and target point sets must have the same non-zero size.");
    //        return;
    //    }

    //    Matrix4x4 transformMatrix = RunICP(sourcePoints, targetPoints, maxIterations, tolerance);
    //    Debug.Log("Final Transformation Matrix:\n" + transformMatrix);
    //}

    /// <summary>
    /// Runs the Iterative Closest Point algorithm for rigid registration.
    /// </summary>
    public Matrix4x4 RunICP(Vector3[] source, Vector3[] target, int maxIter, float tol)
    {
        Vector3[] src = source;
        Matrix4x4 accumulatedTransform = Matrix4x4.identity;

        for (int iter = 0; iter < maxIter; iter++)
        {
            // Step 1: Find closest points
            Vector3[] closestPoints = FindClosestPoints(src, target);

            // Step 2: Compute best-fit transform
            Matrix4x4 transform = ComputeBestFitTransform(src, closestPoints);

            // Step 3: Apply transform to source
            for (int i = 0; i < src.Length; i++)
                src[i] = transform.MultiplyPoint3x4(src[i]);

            // Step 4: Accumulate transformation
            accumulatedTransform = transform * accumulatedTransform;

            // Step 5: Check convergence
            float meanError = ComputeMeanDistance(src, closestPoints);
            if (meanError < tol)
                break;
        }

        return accumulatedTransform;
    }

    /// <summary>
    /// Finds the closest point in target for each point in source.
    /// </summary>
    /// 
    // ******************************************
    //      probably needs to be changed
    // ******************************************
    Vector3[] FindClosestPoints(Vector3[] source, Vector3[] target)
    {
        Vector3[] closest = new Vector3[source.Length];
        int i = 0;
        foreach (var s in source)
        {
            float minDist = float.MaxValue;
            Vector3 bestMatch = Vector3.zero;
            foreach (var t in target)
            {
                float dist = Vector3.SqrMagnitude(s - t);
                if (dist < minDist)
                {
                    minDist = dist;
                    bestMatch = t;
                }
            }
            closest[i] = bestMatch;
            ++i;
        }
        return closest;
    }

    /// <summary>
    /// Computes the rigid transformation (rotation + translation) that best aligns two point sets.
    /// </summary>
    Matrix4x4 ComputeBestFitTransform(Vector3[] src, Vector3[] dst)
    {
        // Compute centroids
        Vector3 centroidSrc = ComputeCentroid(src);
        Vector3 centroidDst = ComputeCentroid(dst);

        // Subtract centroids
        List<Vector3> srcCentered = new List<Vector3>();
        List<Vector3> dstCentered = new List<Vector3>();
        for (int i = 0; i < src.Length; i++)
        {
            srcCentered.Add(src[i] - centroidSrc);
            dstCentered.Add(dst[i] - centroidDst);
        }

        // Compute covariance matrix
        float[,] cov = new float[3, 3];
        for (int i = 0; i < src.Length; i++)
        {
            cov[0, 0] += srcCentered[i].x * dstCentered[i].x;
            cov[0, 1] += srcCentered[i].x * dstCentered[i].y;
            cov[0, 2] += srcCentered[i].x * dstCentered[i].z;

            cov[1, 0] += srcCentered[i].y * dstCentered[i].x;
            cov[1, 1] += srcCentered[i].y * dstCentered[i].y;
            cov[1, 2] += srcCentered[i].y * dstCentered[i].z;

            cov[2, 0] += srcCentered[i].z * dstCentered[i].x;
            cov[2, 1] += srcCentered[i].z * dstCentered[i].y;
            cov[2, 2] += srcCentered[i].z * dstCentered[i].z;
        }

        // Use SVD to find rotation
        Matrix4x4 rotation = Matrix4x4.identity;
        
        // Convert to Unity's Matrix4x4 for SVD
        //Matrix4x4 covMat = new Matrix4x4(
        //    new Vector4(cov[0, 0], cov[1, 0], cov[2, 0], 0),
        //    new Vector4(cov[0, 1], cov[1, 1], cov[2, 1], 0),
        //    new Vector4(cov[0, 2], cov[1, 2], cov[2, 2], 0),
        //    new Vector4(0, 0, 0, 1)
        //);

        // Unity doesn't have built-in SVD — use MathNet.Numerics or custom SVD
        // For simplicity, here we use Quaternion.LookRotation approximation
        Vector3 forward = new Vector3(cov[0, 2], cov[1, 2], cov[2, 2]).normalized;
        Vector3 up = new Vector3(cov[0, 1], cov[1, 1], cov[2, 1]).normalized;
        Quaternion rot = Quaternion.LookRotation(forward, up);
        rotation = Matrix4x4.Rotate(rot);
        

        // Compute translation
        Vector3 translation = centroidDst - rotation.MultiplyPoint3x4(centroidSrc);

        // Build transformation matrix
        Matrix4x4 transform = Matrix4x4.TRS(translation, rotation.rotation, Vector3.one);
        return transform;
    }

    Vector3 ComputeCentroid(Vector3[] points)
    {
        Vector3 sum = Vector3.zero;
        foreach (var p in points) sum += p;
        return sum / points.Length;
    }

    float ComputeMeanDistance(Vector3[] a, Vector3[] b)
    {
        float sum = 0f;
        for (int i = 0; i < a.Length; i++)
            sum += Vector3.Distance(a[i], b[i]);
        return sum / a.Length;
    }
}


//public class PointRegression : MonoBehaviour
//{
//    // we are using Coherent Point Drift (CPD) method for rigid Point Set Registration (PSR)

//    public void getTransform(Vector2[] wallList, Vector2[] matchTo, float noise, float beta, float lambda, int maxIterations)
//    {
//        //# Get shapes
//        //N, D = X.shape
//        //M = Y.shape[0]

//        int D = wallList.Length; // N, D, M
//        //theta = (np.eye(D), np.zeros(D), 1)
//        var theta = (Eye(D),new int[D], 1); //theta = (R, t, s)
        
//        //# Compute isotropic covariances
//        int DIST = 0; // np.sum(cdist(X, Y, metric = 'euclidean') * *2)
//        var isoCovar = 1 / (D * D * D) * DIST;
     
        
//        //# EM optimization

//        for (int iteration = 0; iteration < maxIterations; iteration++)
//        {
//            //# E-step: Compute P
            
//        }

        
        
//        //    P = np.zeros((M, N))
//        //    for n in range(N):
//        //        P[:, n] = np.exp(-1 / (2 * var) * np.sum((X[n] - self.transform(Y, *theta)) * *2, axis = 1))
//        //    P /= np.sum(P, axis = 0) + (2 * np.pi * var) * *(D / 2) * w / (1 - w) * M / N

//        //    # M-step: Solve for (R, t, s), var or (B, t), var
//        //    theta, var = self.solve(X, Y, P)
//        //    if save_parameters:
//        //        self.parameters.append(theta)
//        //    if iteration > 0 and np.allclose(P, P_old, rtol = 1e-5, atol = 1e-4):
//        //        break
//        //    else:
//        //        P_old = np.copy(P)
//        //print(f'Finished after {iteration + 1} iterations.')
//        //return self.transform(Y, *theta), P
//    }

//    public static float[,] Eye(int size)
//    {
//        float[,] matrix = new float[size, size];

//        for (int i = 0; i < size; i++)
//        {
//            int j = i; // column index for the diagonal
//            if (j >= 0 && j < size)
//            {
//                matrix[i, j] = 1f;
//            }
//        }

//        return matrix;
//    }
//    
//}
// https://github.com/tobiasbernecker/PointSetRegistration/blob/master/cpd.ipynb
/*
 * class CPD: 
    '''
        Class implementing the Coherent Point Drift (CPD) method for
        rigid, affine and non-rigid point set registration.
    '''
    def __init__(self, method='rigid'):
        '''
            Initialize CPD class with rigid, affine or non-rigid point set registration.
            
            Parameters
            ----------
            method: str, optional (default: 'rigid')
                    'rigid', 'affine' or 'nonrigid'.
        '''
        self.method = method
        self.solve = self.solve_rigid
        # Y: np.ndarray of shape = (M, D), R: np.ndarray of shape = (D, D), t: np.ndarray of shape = (D,),
        # s: float
        # Returns np.ndarray of shape = (M, D)
        self.transform = lambda Y, R, t, s: s * Y @ R.T + t
        

    def __call__(self, X, Y, w=0.1, beta=2, lmbda=2, max_iterations=100, save_parameters=False):
        '''
            Applies the CPD method to the data in Y to match X.
            
            Parameters
            ----------
            X:                  np.ndarray, shape = (N, D)
                                Set containing N D-dimensional data points.
            Y:                  np.ndarray, shape = (M, D)
                                Set containing M D-dimensional data points.
            w:                  float, optional (default: 0.1)
                                Assumption on the amount of noise in the point sets.
            beta:               float, optional (default: 2)
                                Model of smoothness regularizer (width of Gaussian filter in equation 20).
            lmbda:              float, optional (default: 2)
                                Trade-off between goodness of maximum likelihood fit and regularization.
            max_iterations:     int, optional (default: 2)
                                Maximum number of iterations for the EM optimization.
            save_parameters:    bool, optional (default: False)
                                Whether to save the history of estimated transformation parameters.
            
            Returns
            -------
            Y_aligned:          np.ndarray, shape = (M, D)
                                Aligned Y points.
            P:                  np.ndarray, shape = (M, N)
                                Probabilities for point assignments from Y to X.
        '''
        # Get shapes
        N, D = X.shape
        M = Y.shape[0]
        if self.method == 'rigid':
            # Initialize theta = (R, t, s)
            theta = (np.eye(D), np.zeros(D), 1)
        if save_parameters:
            self.parameters = [theta]
        # Compute isotropic covariances
        var = 1 / (D * N * M) * np.sum(cdist(X, Y, metric='euclidean')**2)
        # EM optimization
        for iteration in range(max_iterations):
            # E-step: Compute P
            P = np.zeros((M, N))
            for n in range(N):
                P[:, n] = np.exp(-1 / (2 * var) * np.sum((X[n] - self.transform(Y, *theta))**2, axis=1))
            P /= np.sum(P, axis=0) + (2 * np.pi * var)**(D / 2) * w / (1 - w) * M / N
            
            # M-step: Solve for (R, t, s), var or (B, t), var
            theta, var = self.solve(X, Y, P)
            if save_parameters:
                self.parameters.append(theta)
            if iteration > 0 and np.allclose(P, P_old, rtol=1e-5, atol=1e-4):
                break
            else:
                P_old = np.copy(P)
        print(f'Finished after {iteration + 1} iterations.')
        return self.transform(Y, *theta), P

    def solve_rigid(self, X, Y, P):
        '''
            Solves for the rigid point set registration.
            
            Parameters
            ----------
            X:                  np.ndarray, shape = (N, D)
                                Set containing N D-dimensional data points.
            Y:                  np.ndarray, shape = (M, D)
                                Set containing M D-dimensional data points.
            P:                  np.ndarray, shape = (M, N)
                                Probabilities for point assignments from Y to X.
                                
            Returns
            -------
            theta:              tuple, length = 3
                                Rotation matrix R: np.ndarray of shape = (D, D)
                                Translation vector t: np.ndarray of shape = (D,)
                                Scale s: float
            var:                float
                                Isotropic covariances.
        '''
        N_P = np.sum(P)
        mu_x = 1 / N_P * X.T @ np.sum(P, axis=0)
        mu_y = 1 / N_P * Y.T @ np.sum(P, axis=1)
        X_hat = X - mu_x
        Y_hat = Y - mu_y
        A = X_hat.T @ P.T @ Y_hat
        # Compute SVD of A
        U, _, V_T = np.linalg.svd(A)
        D = X.shape[1]
        C = np.diag(np.concatenate([np.ones(D-1), np.linalg.det(U @ V_T).reshape(1)]))
        R = U @ C @ V_T
        s = np.trace(A.T @ R) / np.trace(Y_hat.T @ np.diag(np.sum(P, axis=1)) @ Y_hat)
        t = mu_x - s * R @ mu_y
        var = 1 / (N_P * D) * (np.trace(X_hat.T @ np.diag(np.sum(P, axis=0)) @ X_hat) - s * np.trace(A.T @ R))
        return (R, t, s), var
*/
